enum ActionTypes {
  GET_TOKEN_REQUEST = "GET_TOKEN_REQUEST",
  GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS",
  GET_TOKEN_ERROR = "GET_TOKEN_ERROR",

  LOAD_BALANCE_REQUEST = "LOAD_BALANCE_REQUEST",
  LOAD_BALANCE_SUCCESS = "LOAD_BALANCE_SUCCESS",
  LOAD_BALANCE_ERROR = "LOAD_BALANCE_ERROR",

  LOAD_COINS_BALANCES_REQUEST = "LOAD_COINS_BALANCES_REQUEST",
  LOAD_COINS_BALANCES_SUCCESS = "LOAD_COINS_BALANCES_SUCCESS",

  OPEN_CHART_MODAL = "OPEN_CHART_MODAL",
  CLOSE_CHART_MODAL = "CLOSE_CHART_MODAL",
}

export default ActionTypes;