enum ActionTypes {
  LOAD_DEBTS_SUCCESS = "LOAD_DEBTS_SUCCESS",

  LOAD_TRADES_REQUEST = "LOAD_TRADES_REQUEST",
  LOAD_TRADES_SUCCESS = "LOAD_TRADES_SUCCESS",

  REFRESH_CHART_SUCCESS = "REFRESH_CHART_SUCCESS",
  REFRESH_CHART = "REFRESH_CHART",


  GET_TOKEN_REQUEST = "GET_TOKEN_REQUEST",
  GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS",
  GET_TOKEN_ERROR = "GET_TOKEN_ERROR",

  LOAD_BALANCE_REQUEST = "LOAD_BALANCE_REQUEST",
  LOAD_BALANCE_SUCCESS = "LOAD_BALANCE_SUCCESS",
  LOAD_BALANCE_ERROR = "LOAD_BALANCE_ERROR",

  LOAD_COINS_BALANCES_REQUEST = "LOAD_COINS_BALANCES_REQUEST",
  LOAD_COINS_BALANCES_SUCCESS = "LOAD_COINS_BALANCES_SUCCESS",

  OPEN_CHART_MODAL = "OPEN_CHART_MODAL",
  CLOSE_CHART_MODAL = "CLOSE_CHART_MODAL",
}

export default ActionTypes;